{{- range $ns := until (int .Values.config.namespaces) }}
{{- range $proj := until (int $.Values.config.projectsPerNs) }}
{{- range $app := until (int $.Values.config.appsPerProject) }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appofapps-ns{{ $ns }}-p{{ $proj }}-a{{ $app }}
  namespace: openshift-gitops
spec:
  project: project-ns{{ $ns }}-p{{ $proj }}
  source:
    repoURL: {{ $.Values.config.repoURL }}
    targetRevision: {{ $.Values.config.targetRevision }}
    path: gitops-agent/gitops-load-leaf
    helm:
      parameters:
      - name: "appId"
        value: "ns{{ $ns }}-p{{ $proj }}-a{{ $app }}"
      - name: "targetNs"
        value: "target-ns-{{ $ns }}"
      - name: "leafCount"
        value: "{{ $.Values.config.leafAppsPerAppOfApp }}"
      - name: "repoURL"
        value: "{{ $.Values.config.repoURL }}"
      - name: "targetRevision"
        value: "{{ $.Values.config.targetRevision }}"
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
{{- end }}
{{- end }}
{{- end }}
