{{- range $ns := until (int .Values.config.namespaces) }}
{{- range $proj := until (int $.Values.config.projectsPerNs) }}
{{- range $app := until (int $.Values.config.appsPerProject) }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: appofapps-ns{{ $ns }}-p{{ $proj }}-a{{ $app }}
  namespace: {{ $.Values.config.argocdNamespace }}
  labels:
    gitops-load-test: "true"
spec:
  project: approject-{{ add (mod $app 1000) 1 }}
  source:
    repoURL: {{ $.Values.config.repoURL }}
    targetRevision: {{ $.Values.config.targetRevision }}
    path: {{ $.Values.config.basePath }}/gitops-load-leaf
    helm:
      parameters:
      - name: "appId"
        value: "ns{{ $ns }}-p{{ $proj }}-a{{ $app }}"
      - name: "targetNs"
        value: "target-ns-{{ $ns }}"
      - name: "project"
        value: "approject-{{ add (mod $app 1000) 1 }}"
      - name: "leafCount"
        value: "{{ $.Values.config.leafAppsPerAppOfApp }}"
      - name: "repoURL"
        value: "{{ $.Values.config.repoURL }}"
      - name: "targetRevision"
        value: "{{ $.Values.config.targetRevision }}"
      - name: "basePath"
        value: "{{ $.Values.config.basePath }}"
      - name: "argocdNamespace"
        value: "{{ $.Values.config.argocdNamespace }}"
      - name: "automated"
        value: "{{ $.Values.config.automateLeaves }}"
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $.Values.config.argocdNamespace }}
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
{{- end }}
{{- end }}
{{- end }}
