# All of these are overridden by the app-of-apps Helm parameters.
appId: "default"
targetNs: "default"
project: "default"
leafCount: 5
repoURL: "http://gitea.git1.svc:3000/admin/gitops-examples.git"
targetRevision: "main"
basePath: "argocd-agent"
argocdNamespace: "openshift-gitops"
automated: false
