apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core
  namespace: openshift-gitops
spec:
  destination:
    namespace: test
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - group: image.openshift.io
    jsonPointers:
    - /metadata/generation
    - /status/dockerImageRepository
    kind: ImageStream
    namespace: test
  - group: build.openshift.io
    jsonPointers:
    - /metadata/resourceVersion
    - /status/lastVersion
    - /spec/triggers
    kind: BuildConfig
    namespace: test
  - group: apps.openshift.io
    jsonPointers:
    - /metadata/generation
    - /spec/triggers/1/imageChangeParams/lastTriggeredImage
    - /status/latestVersion
    - /status/observedGeneration
    - /status/replicas
    - /status/unavailableReplicas
    - /status/updatedReplicas
    - /status/availableReplicas
    kind: DeploymentConfig
    namespace: test
  - group: extensions
    jsonPointers:
    - /metadata/generation
    kind: Deployment
    namespace: test
  project: default
  source:
    path: ./bc-deployed-manifest
    repoURL: https://github.com/giovannisciortino/gitops-examples.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - RespectIgnoreDifferences=true

