apiVersion: config.openshift.io/v1
kind: Image
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
  name: cluster
spec:
  registrySources:
    allowedRegistries:
    - registry.redhat.io
    - registry.access.redhat.com
    - registry.connect.redhat.com
    - quay.io
    - docker.io
    - k8s.gcr.io
    - gcr.io
    - ghcr.io
    - nvcr.io
    containerRuntimeSearchRegistries:
    - registry.access.redhat.com
    - registry.connect.redhat.com
    - docker.io
