apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- image.yaml
patchesJson6902:
- target:
    group: config.openshift.io
    version: v1
    kind: Image
    name: cluster
    labelSelector: "app.kubernetes.io/instance=sandbox1365-common"
  path: patch.yaml


