apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test2
  namespace: openshift-gitops
spec:
  destination:
    namespace: helloworld2
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./app-helloworld-without-ns-creation
    repoURL: https://github.com/giovannisciortino/gitops-examples.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
