{{- range $leaf := until (int .Values.leafCount) }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: final-app-{{ $.Values.appId }}-leaf{{ $leaf }}
  namespace: {{ $.Values.argocdNamespace }}
  labels:
    gitops-load-test: "true"
spec:
  project: {{ $.Values.project }}
  source:
    repoURL: {{ $.Values.repoURL }}
    targetRevision: {{ $.Values.targetRevision }}
    path: {{ $.Values.basePath }}/gitops-load-dummy-config
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $.Values.targetNs }}
{{- if $.Values.automated }}
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
{{- end }}
{{- end }}
