apiVersion: rbac.authorization.k8s.io/v1
groupNames:
- apps-group1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: admin
  namespace: helloworld
roleRef:
  name: admin
subjects:
- kind: Group
  name: group1
- kind: ServiceAccount
  name: sa1
  namespace: change
userNames:
- system:serviceaccount:change:robot

