apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: root-load-generator
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: "https://gitea-git1.apps.managed1.v6vbg.gcp.redhatworkshops.io/admin/gitops-examples.git"
    targetRevision: "main"
    path: argocd-agent/gitops-load-root
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
