apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: customer-cluster-project
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Argo project
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'

