apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  namespace: openshift-gitops
  name: gsciorti-appset-guestbook
spec:
  generators:
  - list:
      elements:
      - cluster: in-cluster
        url: https://kubernetes.default.svc
        optionNamespaceProject: gsciorti-guestbook
      - cluster: in-cluster
        url: https://kubernetes.default.svc
        optionNamespaceProject: gsciorti-guestbook1
  template:
    metadata:
      name: 'app-gsciorti-{{cluster}}-{{optionNamespaceProject}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/giovannisciortino/gitops-examples.git
        targetRevision: HEAD
        path: chart1
      helm:
        values: |
          {{values}}
      destination:
        server: '{{url}}'
        namespace: '{{optionNamespaceProject}}'

      syncPolicy:
        # Don't delete application when applicationSet is deleted
        preserveResourcesOnDeletion: true
        automated: {}
        syncOptions:
          - CreateNamespace=true