---
apiVersion: v1
kind: Namespace
metadata:
  name: operator-policy-example3
spec: {}
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  namespace: operator-policy-example3
  name: global
spec:
  clusterSet: global
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: operator-policy-example3
  namespace: operator-policy-example3
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-openshift-gitops
        spec:
          remediationAction: inform
          severity: critical
          complianceType: musthave
          upgradeApproval: Automatic
          subscription:
            channel: gitops-1.14
            name: openshift-gitops-operator
            source: redhat-operators
            sourceNamespace: openshift-marketplace
            config:
              env:
              - name: DISABLE_DEFAULT_ARGOCD_INSTANCE
                value: "true"
            startingCSV: openshift-gitops-operator.v1.14.4
          versions:
            - openshift-gitops-operator.v1.14.4


---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: operator-policy-example3
  namespace: operator-policy-example3
placementRef:
  name: operator-policy-example3
  kind: Placement
  apiGroup: cluster.open-cluster-management.io
subjects:
  - name: operator-policy-example3
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: operator-policy-example3
  namespace: operator-policy-example3
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
          - {key: name, operator: In, values: ["local-cluster"]}
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
