apiVersion: v1
items:
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    labels:
      {{- include "chart1.labels" . | nindent 6 }}
    name: {{ include "chart1.fullname" . | trunc 63  }}
    namespace: guestbook
  spec:
    host: short.apps.lab01.gpslab.club
    port:
      targetPort: http
    to:
      kind: Service
      name: {{ include "chart1.fullname" . }}
      weight: 100
    wildcardPolicy: None
kind: List
