apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-set-git-generator-example
  namespace: openshift-gitops
spec:
  goTemplate: true
  generators:
  - git:
      repoURL: https://github.com/giovannisciortino/gitops-examples.git
      revision: HEAD
      files:
      - path: "application-set-git-generator-config/**/config.yaml"
  template:
    metadata:
      name: '{{application.name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/giovannisciortino/gitops-examples.git
        targetRevision: '{{source.targetRevision}}'
        path: 'chart1'
        helm:
          values: |-
            {{chartValues}}
# QUESTO FUNZIONA
#            {{chartValues}}

      destination:
        server: '{{cluster.address}}'
        namespace: guestbook
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
