---
apiVersion: v1
kind: Namespace
metadata:
  name: operator-policy-example1
spec: {}
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  namespace: operator-policy-example1
  name: global
spec:
  clusterSet: global
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: operator-policy-example1
  namespace: operator-policy-example1
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-quay
        spec:
          remediationAction: enforce
          severity: critical
          complianceType: musthave
          upgradeApproval: None
          subscription:
            channel: stable-3.11
            name: quay-operator
            source: redhat-operators
            sourceNamespace: openshift-marketplace
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: operator-policy-example1
  namespace: operator-policy-example1
placementRef:
  name: operator-policy-example1
  kind: Placement
  apiGroup: cluster.open-cluster-management.io
subjects:
  - name: operator-policy-example1
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: operator-policy-example1
  namespace: operator-policy-example1
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
          - {key: name, operator: In, values: ["local-cluster"]}
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
