application:
  name: app2bis
source:
  targetRevision: HEAD
cluster:
  address: https://kubernetes.default.svc
values:
  var1: value2
chartValues: 
  image:
    tag: v4.7.0-202107292319.p0.git.24f464b.assembly.stream
  var1: cluster02value1
  nested1:
    var2: cluster02value2
    var3: cluster02value3
    list1:
      - cluster02value4
      - cluster02value5
      - cluster02value6
  replicaCount: 2
