apiVersion: v1
kind: Secret
metadata:
  name: test-token
  namespace: gsciorti-test-sa
  annotations:
    kubernetes.io/service-account.name: sa-external-app
type: kubernetes.io/service-account-token
