apiVersion: v1
items:
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    labels:
      {{- include "chart-escape-character.labels" . | nindent 6 }}
    name: {{ include "chart-escape-character.fullname" . }}
  spec:
#    host: chart-escape-character-gsciorti-bitnami-charts.apps.lab01.gpslab.club
    port:
      targetPort: http
    to:
      kind: Service
      name: {{ include "chart-escape-character.fullname" . }}
      weight: 100
    wildcardPolicy: None
kind: List
