application:
  name: app1bis
source:
  targetRevision: HEAD
cluster:
  address: https://kubernetes.default.svc
values:
  var1: value1
chartValues: |
  image:
    tag: v4.7.0-202105251845
  var1: cluster01value1
  nested1:
    var2: cluster01value2
    var3: cluster01value3
    list1:
      - cluster01value4
      - cluster01value5
      - cluster01value6
  replicaCount: 3
