apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: managed-gitops-placement
  namespace: openshift-gitops
spec:
  clusterSelector:
    matchLabels:
      vendor: OpenShift